/*
 * NewJFrame.java
 *
 * Created on 18 aprile 2007, 15.21
 */

/*
  ListaFiles by Alberto Panu, alberto@panu.it, http://www.panu.it/
  lists files in folders, calculate md5 sum, and store some files info.
 * 
    Copyright (C) 2009  Alberto Panu

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.


*/

package my.provola;

import com.sun.org.apache.bcel.internal.classfile.JavaClass;
import com.twmacinta.util.*;
import com.twmacinta.io.*;
import java.io.File;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.GregorianCalendar;

/**
 *
 * @author  cdo_panu
 */
public class NewJFrame extends javax.swing.JFrame {
    /** Creates new form NewJFrame */
    public NewJFrame() {
               
        eol = System.getProperty("line.separator");
        //dbconnect = new my.provola.connessione();
        initComponents();
       
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lista files");
        setResizable(false);

        jButton1.setText("Scegli destinazione");
        jButton1.setToolTipText("Per scegliere il file nel quale si vuole salvare la lista.");
        jButton1.setActionCommand("Scegli file");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton2.setText("Scegli cartella");
        jButton2.setToolTipText("Per selezionare la cartella o il disco del quale si vuole l'elenco dei files.");
        jButton2.setActionCommand("jButton2ActionPerformed");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Crea lista");
        jButton3.setToolTipText("Crea la lista, attivo solo se sono stati scelti il file nel quale scrivere e la cartella d'origine.");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Dimensione files");
        jCheckBox1.setToolTipText("Inserisce la dimensione dei files nella lista.");
        jCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setSelected(true);
        jCheckBox2.setText("Ultima modifica");
        jCheckBox2.setToolTipText("Inserisce la data dell'ultima modifica dei files nella lista.");
        jCheckBox2.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jCheckBox3.setText("Hash md5");
        jCheckBox3.setToolTipText("Inserisce lo somma MD5 dei files nella lista.");
        jCheckBox3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setText("Includi path");
        jCheckBox4.setToolTipText("Aggiunge il path completo al nome dei files.");
        jCheckBox4.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jCheckBox5.setText("Solo files");
        jCheckBox5.setToolTipText("Esclude dall'elenco le cartelle.");
        jCheckBox5.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jCheckBox6.setText("Indenta");
        jCheckBox6.setToolTipText("Aggiunge uno spazio prima dei nomi in base alla profonditˆ delle cartelle.");
        jCheckBox6.setMargin(new java.awt.Insets(0, 0, 0, 0));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 249, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                        .add(89, 89, 89)
                        .add(jButton2))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                        .add(70, 70, 70)
                        .add(jButton1)))
                .addContainerGap())
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                        .add(74, 74, 74)
                        .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(24, 24, 24))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jCheckBox3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 256, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jCheckBox4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 256, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jCheckBox5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 256, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jCheckBox6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 256, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jCheckBox1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jCheckBox2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 256, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButton3)
                .add(29, 29, 29)
                .add(jCheckBox1)
                .add(12, 12, 12)
                .add(jCheckBox2)
                .add(11, 11, 11)
                .add(jCheckBox3)
                .add(9, 9, 9)
                .add(jCheckBox4)
                .add(9, 9, 9)
                .add(jCheckBox5)
                .add(9, 9, 9)
                .add(jCheckBox6)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
        boolean errore = false;
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jCheckBox1.setEnabled(false);
        jCheckBox2.setEnabled(false);
        jCheckBox3.setEnabled(false);
        jCheckBox4.setEnabled(false);
        jCheckBox5.setEnabled(false);
        jCheckBox6.setEnabled(false);

        Thread nuovo = new Thread(
            new Runnable () {
                public void run() {
                        String testo;
                        try {
                                uscita = new java.io.FileWriter(destinazione);
                        } catch (java.io.IOException e) {
                            errorazzo(e);  
                            System.exit(1);
                        }
                        
                        if (! jCheckBox5.isSelected()) {
                           
                            
                            if (jCheckBox2.isSelected()) {
                                sdata = new java.util.Date(file.lastModified());
                                testo = "\t" + sdata.toLocaleString();
                            } else {
                                testo = "";
                            }
                            
                            try {
                                if (jCheckBox4.isSelected()) {
                                    uscita.write(file.getAbsolutePath() + file.separator + testo + eol);
                                } else {
                                    uscita.write(file.getName() + file.separator + testo + eol);
                                }
                            } catch (java.io.IOException e) {
                                errorazzo(e);
                                System.exit(6);                                     
                            }
                        }
                        
                          scanna(file, "");
                        
                          try {
                                uscita.close();
                          } catch (java.io.IOException e) {
                              errorazzo(e);
                              System.exit(2);
                          }
                          
                          txtfile = false;
                          cartella = false;
                          jLabel2.setText("");
                          jLabel3.setText("");
                          jButton1.setEnabled(true);
                          jButton2.setEnabled(true);
                          jCheckBox1.setEnabled(true);
                          jCheckBox2.setEnabled(true);
                          jCheckBox3.setEnabled(true);
                          jCheckBox4.setEnabled(true);
                          jCheckBox5.setEnabled(true);
                          jCheckBox6.setEnabled(true);
                }
            }
        );
        nuovo.start();
        

        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
        fc = new javax.swing.JFileChooser();
        //fc.setDialogType(javax.swing.JFileChooser.OPEN_DIALOG);
        fc.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        fc.setDialogTitle("Scegli la cartella");
        int returnVal = fc.showOpenDialog(NewJFrame.this);
        if (returnVal == fc.APPROVE_OPTION) {
            file = fc.getSelectedFile();
            jLabel2.setText(file.getName());
            jLabel2.setToolTipText(file.getAbsolutePath());
            //jButton1.setEnabled(true);
            cartella = true;
            if (txtfile == true) {
                jButton3.setEnabled(true);
            }
        } else {
            jLabel2.setText("");
            jLabel2.setToolTipText("");
            //jButton1.setEnabled(false);
            cartella = false;
            jButton3.setEnabled(false);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        calendario = new GregorianCalendar();
        fc = new javax.swing.JFileChooser();
        //fc.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        fc.setFileSelectionMode(fc.FILES_ONLY);
        fc.setDialogTitle("Scegli il file di destinazione");
        Integer anno;
        anno = calendario.get(calendario.YEAR);
        Integer mese;
        mese = calendario.get(calendario.MONTH);
        mese++;
        Integer giorno;
        giorno = calendario.get(calendario.DAY_OF_MONTH );
        String nomefile;
        nomefile = anno.toString();
        if (mese < 10) {
            nomefile = nomefile + "0";
        }
        nomefile = nomefile + mese;
        if (giorno < 10) {
            nomefile = nomefile + "0";
        }
        nomefile = nomefile + giorno + ".txt" ;
        fc.setSelectedFile(new File( nomefile ));
        boolean fai;
        int returnVal = fc.showSaveDialog(NewJFrame.this);
        if (returnVal == fc.APPROVE_OPTION) {
           destinazione = fc.getSelectedFile();
           if (destinazione != null && destinazione.exists()) {
               int answer = showSaveDisplayQuestion(destinazione);
               if (answer == javax.swing.JOptionPane.YES_OPTION) {
                   fai = true;
               } else {
                   fai = false;   
               }       
           } else {
               fai = true;
           }

        } else {
            fai = false;
        }
        
        if (fai) {
        //   jLabel3.setText(destinazione.getAbsolutePath());
           jLabel3.setText(destinazione.getName() );
           jLabel3.setToolTipText(destinazione.getAbsolutePath());
           txtfile = true;
           if (cartella == true) {
                jButton3.setEnabled(true);
           }
           
        } else {
           jLabel3.setText("");
           jLabel3.setToolTipText("");
           txtfile = false;
           jButton3.setEnabled(false);
        }
        
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed
    
    private void scanna(java.io.File cannello, String memstringa) {
        java.lang.String contenuto[];    
        java.io.File miofile;
        contenuto = cannello.list();
        String testo;
        String stringa;
        if (jCheckBox6.isSelected()) {
            stringa = memstringa + "\t";
        } else {
            stringa = memstringa;
        }       
        for ( int i = 0; i < contenuto.length; i ++ ) {
            miofile = new java.io.File(cannello.getAbsolutePath() + cannello.separator + contenuto[i]);
            if (miofile.getName().charAt(0) != '.' ) {
                sdata = new java.util.Date(miofile.lastModified());
                jLabel2.setText(miofile.getName());
                if (jCheckBox4.isSelected()) {
                    testo = stringa + miofile.getAbsolutePath();
                } else {
                    testo = stringa + miofile.getName();
                }
                if (miofile.isDirectory()) {
             //   jTextArea1.setText(jTextArea1.getText() + "Directory"  + "\n");
                    if (! jCheckBox5.isSelected()) {
                        testo = testo + cannello.separator;
                        if (jCheckBox2.isSelected()) {
                            testo = testo + "\t" + sdata.toLocaleString();
                        }
                        testo = testo + eol;
                        try {
                            uscita.write(testo);
                        } catch (java.io.IOException e) {
                            errorazzo(e);
                            System.exit(3);                                     
                        }
                    }
                    scanna(miofile, stringa);
                } else {
            //jTextArea1.setText(jTextArea1.getText() + file.getAbsolutePath() + "/" + contenuto[i] + "\n");
              //  jTextArea1.setText(jTextArea1.getText() + miofile.getAbsolutePath() + "\t" + miofile.length() + "\n");  
                    
                    if (jCheckBox1.isSelected()) {
                        testo = testo + "\t" + formatter.format(miofile.length());
                    }
                    if (jCheckBox2.isSelected()) {
                        testo = testo + "\t" + sdata.toLocaleString();
                    }
                    try {
                        
                        if (jCheckBox3.isSelected()) {
                            testo = testo + "\t" + MD5.asHex(MD5.getHash(miofile)); 
                        }
                        
                        testo = testo + eol;
                        
                        try {
                            uscita.write(testo);
                        } catch (java.io.IOException e) {
                            errorazzo(e);
                            System.exit(5);                                      
                        }
                    } catch (java.io.IOException e) {
                        errorazzo(e);
                        System.exit(4);                                      
                    }       
                        

                }
            }

        }
    
    }
    
    private int showSaveDisplayQuestion(java.io.File file) {
	String message = "Il file " + file.getAbsolutePath() + 
				" esiste. Volete sovrascriverlo?";
	return javax.swing.JOptionPane.showOptionDialog(NewJFrame.this,
					    message,
					    "Avvertenza sul salvataggio",
					    javax.swing.JOptionPane.YES_NO_OPTION,
					    javax.swing.JOptionPane.WARNING_MESSAGE,
					    null,
					    null,
					    null);
    }
    
    private void errorazzo(java.io.IOException errore) {
        javax.swing.JOptionPane.showMessageDialog(NewJFrame.this, errore.getLocalizedMessage(), "Errorazzo!", javax.swing.JOptionPane.ERROR_MESSAGE );
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JFileChooser fc;
    private java.util.Calendar calendario;
    private java.io.File destinazione;
    private java.io.File file;
    private boolean cartella;
    private boolean txtfile;
    private java.io.FileWriter uscita;
    private java.util.Date sdata;
    private String eol;
    private NumberFormat formatter = new DecimalFormat("#,###,###");
    //private static Thread nuovo;
    //private my.provola.connessione dbconnect;
    //private java.lang.String contenuto[]; 
    
}
